nyc_parking_violations:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: transformed-data-455317   # ✅ your GCP project
      dataset: dbt_hajmerwala            # ✅ your BQ dataset
      threads: 4
      timeout_seconds: 300
      location: US                       # or whatever region your dataset is in
  target: dev
