# .github/workflows/run-dbt-prod.yml
name: run_dbt_prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  DBT_PROFILES_DIR: ./nyc_parking_violations
  DBT_PROJECT_DIR: ./nyc_parking_violations

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-duckdb==1.6.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: List files to check profiles.yml location
      run: ls -alh ./nyc_parking_violations

    - name: Clean target directory
      run: rm -rf ./target

    - name: Run dbt debug
      run: dbt debug --target prod

    - name: Run dbt compile
      run: dbt compile --target prod

    - name: Run dbt run
      run: dbt run --target prod

    - name: Run dbt tests
      run: dbt test --target prod
